//! The 64×64 panel's text-size tiers as bitmap fonts (brief 3, 1.4).
//!
//! A downsampled vector font smears at these sizes on a 64×64 RGB panel, so
//! each tier gets its own one-bit cut of Space Grotesk 700, rasterised at the
//! size whose capital H comes out exactly the tier's cap height, then
//! hinted: thresholded, ascenders snapped down to the cap line, and every
//! glyph cut to its ink. The cuts are written out as pixel art
//! (`packages/firmware/core/src/tier64.rs`) so a pixel can still be edited by
//! hand; a test keeps that file in step with this generator.
//!
//! `UPDATE_TIER_FONTS=1 cargo test -p smokebomb-assets-build tier` rewrites it.

use std::fmt::Write;

/// One cut: its name, cap height in panel px, and the gap between glyphs.
pub struct Cut {
    pub name: &'static str,
    pub doc: &'static str,
    pub cap: usize,
    pub gap: u8,
}

/// The cuts the 64×64 screens use (cap heights for the 30 mm build, 0.168
/// mm pitch). H2 is the hand-drawn 5×7 `TEXT`, and T1's digits are the
/// hand-drawn result numerals.
pub const CUTS: [Cut; 3] = [
    Cut {
        name: "T2",
        doc: "T2, a word on a table screen: 15 px caps (2.5 mm).",
        cap: 15,
        gap: 1,
    },
    Cut {
        name: "H1",
        doc: "H1, the value on a held screen: 18 px caps (3.0 mm).",
        cap: 18,
        gap: 1,
    },
    Cut {
        name: "T1",
        doc: "T1 at its floor, for letters and signs on a table screen: 21 px caps (3.5 mm).",
        cap: 21,
        gap: 2,
    },
];

/// Coverage at or above this (of 255) lights a pixel.
const THRESHOLD: u8 = 112;

/// Printable ASCII and the few other characters the screens use.
fn chars() -> Vec<char> {
    let mut v: Vec<char> = (' '..='~').collect();
    v.extend(['−', '×', '·']);
    v
}

/// A glyph's lit pixels, rows from the cap line down, and its width.
struct Bits {
    width: usize,
    rows: Vec<Vec<bool>>,
}

/// Rasterise `c` at `px`, placed on a box `cap` rows above the baseline and
/// `desc` below. Ink above the cap line is snapped down onto it.
fn raster(font: &fontdue::Font, c: char, px: f32, cap: usize, desc: usize, advance: bool) -> Bits {
    let (m, bitmap) = font.rasterize(c, px);
    let h = cap + desc;
    let mut rows = vec![vec![false; m.width.max(1)]; h];
    for y in 0..m.height {
        // Row `y` of the bitmap sits this far above the baseline.
        let above = m.ymin + (m.height - y) as i32;
        let row = (cap as i32 - above).clamp(0, h as i32 - 1) as usize;
        for x in 0..m.width {
            if bitmap[y * m.width + x] >= THRESHOLD {
                rows[row][x] = true;
            }
        }
    }
    // Cut to the ink, left and right.
    let lit = |x: usize| rows.iter().any(|r| r[x]);
    let w = rows[0].len();
    let first = (0..w).find(|&x| lit(x));
    let last = (0..w).rev().find(|&x| lit(x));
    match (first, last) {
        (Some(a), Some(b)) => Bits {
            width: b - a + 1,
            rows: rows.into_iter().map(|r| r[a..=b].to_vec()).collect(),
        },
        // Nothing lit (a space): as wide as its advance.
        _ => {
            let width = if advance {
                m.advance_width.round().max(1.0) as usize
            } else {
                1
            };
            Bits {
                width,
                rows: vec![vec![false; width]; h],
            }
        }
    }
}

/// The ink height of a capital H at `px`, after thresholding.
fn cap_height(font: &fontdue::Font, px: f32) -> usize {
    let (m, bitmap) = font.rasterize('H', px);
    (0..m.height)
        .filter(|&y| (0..m.width).any(|x| bitmap[y * m.width + x] >= THRESHOLD))
        .count()
}

/// The smallest size whose H is exactly `cap` rows.
fn size_for(font: &fontdue::Font, cap: usize) -> f32 {
    let mut px = cap as f32;
    while cap_height(font, px) < cap {
        px += 0.05;
    }
    px
}

fn char_literal(c: char) -> String {
    match c {
        '\'' => "'\\''".into(),
        '\\' => "'\\\\'".into(),
        c => format!("'{c}'"),
    }
}

/// The Rust source of every cut.
pub fn source(sfnt: &[u8]) -> String {
    let font = fontdue::Font::from_bytes(sfnt, fontdue::FontSettings::default()).expect("font parses");
    let chars: Vec<char> = chars()
        .into_iter()
        .filter(|&c| c == ' ' || font.lookup_glyph_index(c) != 0)
        .collect();
    let mut out = String::new();
    out.push_str(
        "//! The 64×64 panel's text tiers: one-bit cuts of Space Grotesk 700, one per\n\
         //! tier (brief 3, 1.4). GENERATED by `smokebomb-assets-build`\n\
         //! (`tier_fonts.rs`) at the size whose capital H is exactly the tier's cap\n\
         //! height, thresholded and with ascenders snapped to the cap line. Edit a\n\
         //! `#` to hint a glyph by hand, then teach the generator the same change:\n\
         //! a test fails while the two differ.\n\n\
         use crate::font64::{glyph, BitFont, Glyph};\n",
    );
    for cut in &CUTS {
        let px = size_for(&font, cut.cap);
        // Room below the baseline for the deepest descender.
        let desc = chars
            .iter()
            .map(|&c| {
                let (m, bitmap) = font.rasterize(c, px);
                (0..m.height)
                    .filter(|&y| (0..m.width).any(|x| bitmap[y * m.width + x] >= THRESHOLD))
                    .map(|y| -(m.ymin + (m.height - y) as i32 - 1))
                    .max()
                    .unwrap_or(0)
                    .max(0) as usize
            })
            .max()
            .unwrap_or(0);
        let h = cut.cap + desc;
        let glyphs: Vec<(char, Bits)> = chars
            .iter()
            .map(|&c| (c, raster(&font, c, px, cut.cap, desc, true)))
            .collect();
        let name = cut.name;
        let _ = write!(
            out,
            "\n/// {}\npub static {name}: BitFont<{h}> = BitFont {{\n    glyphs: &{name}_GLYPHS,\n    cap: {},\n    gap: {},\n    caps_only: false,\n}};\n\n",
            cut.doc, cut.cap, cut.gap
        );
        let _ = writeln!(out, "static {name}_GLYPHS: [Glyph<{h}>; {}] = [", glyphs.len());
        for (c, bits) in &glyphs {
            assert!(
                bits.width <= 32,
                "{c:?} is {} px wide at {} px caps",
                bits.width,
                cut.cap
            );
            let art: Vec<String> = bits
                .rows
                .iter()
                .map(|r| r.iter().map(|&b| if b { '#' } else { '.' }).collect())
                .collect();
            let _ = writeln!(out, "    glyph(\n        {},", char_literal(*c));
            let _ = writeln!(out, "        \"{}\",", art.join(" "));
            out.push_str("    ),\n");
        }
        out.push_str("];\n");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    const PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../core/src/tier64.rs");

    fn generated() -> String {
        let sfnt = crate::woff_to_sfnt(crate::SPACE_GROTESK_BOLD_WOFF).expect("woff decodes");
        source(&sfnt)
    }

    #[test]
    fn tier_fonts_match_the_generator() {
        let fresh = generated();
        if std::env::var_os("UPDATE_TIER_FONTS").is_some() {
            std::fs::write(PATH, &fresh).expect("writing tier64.rs");
            return;
        }
        let committed = std::fs::read_to_string(PATH).unwrap_or_default();
        assert!(
            committed == fresh,
            "tier64.rs is out of date: UPDATE_TIER_FONTS=1 cargo test -p smokebomb-assets-build tier"
        );
    }

    #[test]
    fn each_cut_has_its_cap_height() {
        let sfnt = crate::woff_to_sfnt(crate::SPACE_GROTESK_BOLD_WOFF).unwrap();
        let font = fontdue::Font::from_bytes(sfnt.as_slice(), fontdue::FontSettings::default()).unwrap();
        for cut in &CUTS {
            assert_eq!(
                cap_height(&font, size_for(&font, cut.cap)),
                cut.cap,
                "{}",
                cut.name
            );
        }
    }
}
